### ISSUE TITLE
Like a song

### ISSUE THREAD

**Issue by davidmoina** [davidmoina/Apollofy-music-app#28]
The user will be able to "Like" the songs, automatically saving them in the "My songs" section.
 Parent:
- https://github.com/davidmoina/Apollofy-music-app/issues/26

**Comment by RubenZafra** [comment]
Also added onclick and mouse events. 

When you hover you see the play button, when its clicked a pause button shows instead and when you press it again it goes back to normal. 

Missing player context to make it all work.
